/** Pakistani-style generic reviews in 3 collections. All 5-star. Admin can assign to products. */
export const SEED_REVIEWS: Array<{ authorName: string; rating: number; body: string; collection: string }> = [
  // ——— collection: quality (40)
  { authorName: 'Ahmed K., Lahore', rating: 5, body: 'Product quality bahut acha hai. Packaging bhi theek thi.', collection: 'quality' },
  { authorName: 'Fatima R., Karachi', rating: 5, body: 'Genuine herbal oil, smell and texture both natural. Very satisfied.', collection: 'quality' },
  { authorName: 'Hassan M., Islamabad', rating: 5, body: 'Premium feel, no fake smell. Will order again.', collection: 'quality' },
  { authorName: 'Ayesha S., Faisalabad', rating: 5, body: 'Quality product, exactly as described. Trusted brand.', collection: 'quality' },
  { authorName: 'Usman T., Rawalpindi', rating: 5, body: 'Original product, packed well. No complaints.', collection: 'quality' },
  { authorName: 'Zainab A., Multan', rating: 5, body: 'Natural ingredients clearly visible. Good quality control.', collection: 'quality' },
  { authorName: 'Bilal H., Peshawar', rating: 5, body: 'Authentic herbal oil. Packaging secure.', collection: 'quality' },
  { authorName: 'Sana N., Quetta', rating: 5, body: 'Quality meets expectations. Genuine product.', collection: 'quality' },
  { authorName: 'Omar F., Sialkot', rating: 5, body: 'Top quality, no compromise. Recommended.', collection: 'quality' },
  { authorName: 'Mariam W., Gujranwala', rating: 5, body: 'Clean formula, no harsh chemicals. Love it.', collection: 'quality' },
  { authorName: 'Imran D., Lahore', rating: 5, body: 'Consistent quality every time. Trust this brand.', collection: 'quality' },
  { authorName: 'Sara G., Karachi', rating: 5, body: 'Premium quality at par with description. Happy customer.', collection: 'quality' },
  { authorName: 'Ali Z., Hyderabad', rating: 5, body: 'Pure herbal, no additives. Quality product.', collection: 'quality' },
  { authorName: 'Hina P., Faisalabad', rating: 5, body: 'Well packed and fresh. Quality maintained.', collection: 'quality' },
  { authorName: 'Kamran L., Islamabad', rating: 5, body: 'Authentic and high quality. Will recommend.', collection: 'quality' },
  { authorName: 'Nadia Q., Rawalpindi', rating: 5, body: 'Good texture and smell. Clearly natural product.', collection: 'quality' },
  { authorName: 'Rashid J., Multan', rating: 5, body: 'Quality product, fast delivery. Satisfied.', collection: 'quality' },
  { authorName: 'Amina B., Peshawar', rating: 5, body: 'Original formula, no fake. Quality assured.', collection: 'quality' },
  { authorName: 'Tariq C., Quetta', rating: 5, body: 'Premium quality herbal oil. Worth every rupee.', collection: 'quality' },
  { authorName: 'Layla E., Sialkot', rating: 5, body: 'Natural and effective. Quality is top notch.', collection: 'quality' },
  { authorName: 'Waqas U., Gujranwala', rating: 5, body: 'Genuine product, sealed properly. Trustworthy.', collection: 'quality' },
  { authorName: 'Nadia V., Lahore', rating: 5, body: 'Clean ingredients, no side effects. Quality first.', collection: 'quality' },
  { authorName: 'Farhan X., Karachi', rating: 5, body: 'Consistent quality. Packaging excellent.', collection: 'quality' },
  { authorName: 'Zara Y., Faisalabad', rating: 5, body: 'Pure herbal blend. Quality as promised.', collection: 'quality' },
  { authorName: 'Saad I., Islamabad', rating: 5, body: 'Authentic and well made. No compromise on quality.', collection: 'quality' },
  { authorName: 'Hira O., Rawalpindi', rating: 5, body: 'Natural smell and feel. Quality product.', collection: 'quality' },
  { authorName: 'Asad R., Multan', rating: 5, body: 'Original packaging, genuine product. Happy.', collection: 'quality' },
  { authorName: 'Mehak T., Peshawar', rating: 5, body: 'Good quality oil, smooth texture. Recommended.', collection: 'quality' },
  { authorName: 'Faisal K., Quetta', rating: 5, body: 'Premium quality. Will buy again.', collection: 'quality' },
  { authorName: 'Aisha M., Sialkot', rating: 5, body: 'Pure and natural. Quality meets standard.', collection: 'quality' },
  { authorName: 'Hamza S., Gujranwala', rating: 5, body: 'Authentic herbal. No fake smell. Good quality.', collection: 'quality' },
  { authorName: 'Zoya N., Lahore', rating: 5, body: 'Well formulated, quality packaging. Satisfied.', collection: 'quality' },
  { authorName: 'Adnan F., Karachi', rating: 5, body: 'Genuine product. Quality consistent.', collection: 'quality' },
  { authorName: 'Anum H., Faisalabad', rating: 5, body: 'Natural ingredients, good quality. Trust this.', collection: 'quality' },
  { authorName: 'Babar J., Islamabad', rating: 5, body: 'Original and premium. Quality delivered.', collection: 'quality' },
  { authorName: 'Dua L., Rawalpindi', rating: 5, body: 'Clean product, no chemicals. Quality assured.', collection: 'quality' },
  { authorName: 'Haris P., Multan', rating: 5, body: 'Pure herbal, well packed. Good quality.', collection: 'quality' },
  { authorName: 'Iqra R., Peshawar', rating: 5, body: 'Authentic formula. Quality as described.', collection: 'quality' },
  { authorName: 'Junaid W., Quetta', rating: 5, body: 'Premium feel, natural. Quality product.', collection: 'quality' },
  // ——— collection: pain_relief (40)
  { authorName: 'Khalid A., Lahore', rating: 5, body: 'Back pain mein kaam aaya. Relief mila within days.', collection: 'pain_relief' },
  { authorName: 'Saima B., Karachi', rating: 5, body: 'Joint pain ke liye best. Natural relief.', collection: 'pain_relief' },
  { authorName: 'Nadeem C., Islamabad', rating: 5, body: 'Muscle pain pe kaam karta hai. Effective oil.', collection: 'pain_relief' },
  { authorName: 'Rukhsar D., Faisalabad', rating: 5, body: 'Knee pain mein relief mila. Recommend for arthritis.', collection: 'pain_relief' },
  { authorName: 'Shahid E., Rawalpindi', rating: 5, body: 'Dad ke liye liya, back pain mein fayda hua.', collection: 'pain_relief' },
  { authorName: 'Tahira F., Multan', rating: 5, body: 'Neck pain ke liye use kiya, relief mila. Good product.', collection: 'pain_relief' },
  { authorName: 'Younis G., Peshawar', rating: 5, body: 'Herbal and effective. Pain relief real hai.', collection: 'pain_relief' },
  { authorName: 'Amna H., Quetta', rating: 5, body: 'Shoulder pain mein kaam aaya. Natural relief.', collection: 'pain_relief' },
  { authorName: 'Noman I., Sialkot', rating: 5, body: 'Sport injury ke baad use kiya. Recovery better hui.', collection: 'pain_relief' },
  { authorName: 'Bushra J., Gujranwala', rating: 5, body: 'Maa ke joint pain ke liye. She is feeling better.', collection: 'pain_relief' },
  { authorName: 'Chaudhry K., Lahore', rating: 5, body: 'Effective for muscle and joint. Pain relief genuine.', collection: 'pain_relief' },
  { authorName: 'Durdana L., Karachi', rating: 5, body: 'Arthritis pain mein relief. Natural formula works.', collection: 'pain_relief' },
  { authorName: 'Ehsan M., Islamabad', rating: 5, body: 'Back ache pe daily use. Comfort mil raha hai.', collection: 'pain_relief' },
  { authorName: 'Fozia N., Faisalabad', rating: 5, body: 'Leg pain ke liye best. Herbal and safe.', collection: 'pain_relief' },
  { authorName: 'Gulzar O., Rawalpindi', rating: 5, body: 'Old age joint pain mein fayda. Recommend.', collection: 'pain_relief' },
  { authorName: 'Huma P., Multan', rating: 5, body: 'Office work se neck pain. This oil helped.', collection: 'pain_relief' },
  { authorName: 'Irfan Q., Peshawar', rating: 5, body: 'Muscle strain pe use kiya. Relief fast.', collection: 'pain_relief' },
  { authorName: 'Javeria R., Quetta', rating: 5, body: 'Knee pain relief. Natural and effective.', collection: 'pain_relief' },
  { authorName: 'Kashif S., Sialkot', rating: 5, body: 'Sports pain ke liye best. No side effects.', collection: 'pain_relief' },
  { authorName: 'Laiba T., Gujranwala', rating: 5, body: 'Mama ke liye liya. Arthritis pain better.', collection: 'pain_relief' },
  { authorName: 'Maqsood U., Lahore', rating: 5, body: 'Chronic back pain mein relief. Trust this oil.', collection: 'pain_relief' },
  { authorName: 'Noreen V., Karachi', rating: 5, body: 'Shoulder stiffness pe kaam karta hai. Good.', collection: 'pain_relief' },
  { authorName: 'Obaid W., Islamabad', rating: 5, body: 'Pain relief real hai. Herbal and safe.', collection: 'pain_relief' },
  { authorName: 'Parveen X., Faisalabad', rating: 5, body: 'Feet pain ke liye use kiya. Relief mila.', collection: 'pain_relief' },
  { authorName: 'Qasim Y., Rawalpindi', rating: 5, body: 'Body pain overall. Effective formula.', collection: 'pain_relief' },
  { authorName: 'Rashida Z., Multan', rating: 5, body: 'Wrist pain mein fayda. Natural relief.', collection: 'pain_relief' },
  { authorName: 'Salman A., Peshawar', rating: 5, body: 'Lower back pain ke liye best. Recommend.', collection: 'pain_relief' },
  { authorName: 'Tasneem B., Quetta', rating: 5, body: 'Joint and muscle dono pe kaam karta hai.', collection: 'pain_relief' },
  { authorName: 'Umar C., Sialkot', rating: 5, body: 'Pain relief fast. Herbal so safe for long use.', collection: 'pain_relief' },
  { authorName: 'Varda D., Gujranwala', rating: 5, body: 'Elderly parents ke liye. Pain mein relief.', collection: 'pain_relief' },
  { authorName: 'Waqar E., Lahore', rating: 5, body: 'Effective pain relief. No chemicals.', collection: 'pain_relief' },
  { authorName: 'Yasmin F., Karachi', rating: 5, body: 'Neck and shoulder pain. This oil works.', collection: 'pain_relief' },
  { authorName: 'Zubair G., Islamabad', rating: 5, body: 'Muscle pain relief natural way. Good product.', collection: 'pain_relief' },
  { authorName: 'Aqsa H., Faisalabad', rating: 5, body: 'Back pain daily use. Feeling better.', collection: 'pain_relief' },
  { authorName: 'Basit I., Rawalpindi', rating: 5, body: 'Knee pain relief. Herbal and effective.', collection: 'pain_relief' },
  { authorName: 'Farah J., Multan', rating: 5, body: 'Pain relief as promised. Natural formula.', collection: 'pain_relief' },
  { authorName: 'Gohar K., Peshawar', rating: 5, body: 'Joint pain ke liye best oil. Recommend.', collection: 'pain_relief' },
  { authorName: 'Hina L., Quetta', rating: 5, body: 'Muscle ache pe kaam aaya. Relief mila.', collection: 'pain_relief' },
  { authorName: 'Jamil M., Sialkot', rating: 5, body: 'Effective for pain. Will buy again.', collection: 'pain_relief' },
  { authorName: 'Kiran N., Gujranwala', rating: 5, body: 'Natural pain relief. No side effects.', collection: 'pain_relief' },
  { authorName: 'Lubna O., Lahore', rating: 5, body: 'Back and knee pain. This oil helped both.', collection: 'pain_relief' },
  { authorName: 'Majid P., Karachi', rating: 5, body: 'Pain relief real. Herbal and trusted.', collection: 'pain_relief' },
  // ——— collection: value (35)
  { authorName: 'Nazia Q., Islamabad', rating: 5, body: 'Price theek hai quality ke hisaab se. Value for money.', collection: 'value' },
  { authorName: 'Rizwan R., Faisalabad', rating: 5, body: 'Worth every rupee. Good product at fair price.', collection: 'value' },
  { authorName: 'Sadia S., Rawalpindi', rating: 5, body: 'Reasonable price, premium quality. Best value.', collection: 'value' },
  { authorName: 'Tariq T., Multan', rating: 5, body: 'Affordable and effective. Value buy.', collection: 'value' },
  { authorName: 'Uzma U., Peshawar', rating: 5, body: 'Price sahi hai. Quality bhi achi. Value for money.', collection: 'value' },
  { authorName: 'Vicky V., Quetta', rating: 5, body: 'Worth the price. Good value product.', collection: 'value' },
  { authorName: 'Warda W., Sialkot', rating: 5, body: 'Reasonable rate, genuine product. Value buy.', collection: 'value' },
  { authorName: 'Xeeshan X., Gujranwala', rating: 5, body: 'Fair price for this quality. Happy with value.', collection: 'value' },
  { authorName: 'Yasir Y., Lahore', rating: 5, body: 'Best value in market. Quality at good price.', collection: 'value' },
  { authorName: 'Zahra Z., Karachi', rating: 5, body: 'Price kam hai quality zyada. Value for money.', collection: 'value' },
  { authorName: 'Akram A., Islamabad', rating: 5, body: 'Worth it. No regret. Good value.', collection: 'value' },
  { authorName: 'Bushra B., Faisalabad', rating: 5, body: 'Reasonable price. Quality product. Value buy.', collection: 'value' },
  { authorName: 'Danish C., Rawalpindi', rating: 5, body: 'Affordable herbal oil. Good value.', collection: 'value' },
  { authorName: 'Erum D., Multan', rating: 5, body: 'Price theek hai. Value for money product.', collection: 'value' },
  { authorName: 'Fahad E., Peshawar', rating: 5, body: 'Worth every penny. Value and quality.', collection: 'value' },
  { authorName: 'Gulnaz F., Quetta', rating: 5, body: 'Fair price. Good quality. Best value.', collection: 'value' },
  { authorName: 'Hassan G., Sialkot', rating: 5, body: 'Reasonable rate for premium product. Value.', collection: 'value' },
  { authorName: 'Iram H., Gujranwala', rating: 5, body: 'Price sahi, quality achi. Value for money.', collection: 'value' },
  { authorName: 'Javed I., Lahore', rating: 5, body: 'Best value in category. Recommend.', collection: 'value' },
  { authorName: 'Kalsoom J., Karachi', rating: 5, body: 'Worth the price. Good value product.', collection: 'value' },
  { authorName: 'Luqman K., Islamabad', rating: 5, body: 'Affordable and effective. Value buy.', collection: 'value' },
  { authorName: 'Munira L., Faisalabad', rating: 5, body: 'Reasonable price. Quality delivered. Value.', collection: 'value' },
  { authorName: 'Naveed M., Rawalpindi', rating: 5, body: 'Good value for money. Satisfied.', collection: 'value' },
  { authorName: 'Palwasha N., Multan', rating: 5, body: 'Price fair hai. Value product.', collection: 'value' },
  { authorName: 'Qaiser O., Peshawar', rating: 5, body: 'Worth it. Value and quality both.', collection: 'value' },
  { authorName: 'Rukhsar P., Quetta', rating: 5, body: 'Best value. Good price and quality.', collection: 'value' },
  { authorName: 'Shazia Q., Sialkot', rating: 5, body: 'Value for money. No complaint.', collection: 'value' },
  { authorName: 'Talha R., Gujranwala', rating: 5, body: 'Reasonable rate. Premium feel. Value.', collection: 'value' },
  { authorName: 'Urooj S., Lahore', rating: 5, body: 'Affordable premium product. Value buy.', collection: 'value' },
  { authorName: 'Waseem T., Karachi', rating: 5, body: 'Price theek quality achi. Value for money.', collection: 'value' },
  { authorName: 'Zainab U., Islamabad', rating: 5, body: 'Worth the price. Good value.', collection: 'value' },
  { authorName: 'Arsalan V., Faisalabad', rating: 5, body: 'Best value in market. Happy.', collection: 'value' },
  { authorName: 'Bisma W., Rawalpindi', rating: 5, body: 'Value and quality. Recommend.', collection: 'value' },
  { authorName: 'Fahad X., Multan', rating: 5, body: 'Fair price. Good product. Value.', collection: 'value' },
  { authorName: 'Hina Y., Peshawar', rating: 5, body: 'Reasonable and effective. Value buy.', collection: 'value' },
  { authorName: 'Imran Z., Quetta', rating: 5, body: 'Worth every rupee. Value product.', collection: 'value' },
];
